# Generated by Django 4.1.7 on 2023-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='org_dp',
            field=models.ImageField(blank=True, default='defaults/default_group.png', null=True, upload_to='org_profile/'),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/default_org_cover.jpeg', upload_to='org_covers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/default-user-cover.png', upload_to='user_covers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='defaults/no_pic.png', upload_to='profile_pic/'),
        ),
    ]
