# Generated by Django 4.1.7 on 2023-03-29 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0003_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biodata',
        ),
        migrations.AlterField(
            model_name='orgs',
            name='biodata',
            field=models.TextField(blank=True, default='we would love to welcome you to our community', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='hey, this is my synergy profile', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_block',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_reported',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
